In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/raw/raw_data.csv")

print(df.shape)
df.head()

(10000, 26)

,record_id,year,state,district,season,crop_type,sowing_date,seed_variety,area_sown_hectares,irrigation_type,...,soil_ph,nitrogen_kg_ha,phosphorus_kg_ha,potassium_kg_ha,soil_type,soil_moisture_pct,previous_yield_tonnes_ha,yield_trend_pct_yoy,ndvi,yield_tonnes_per_hectare
0,AGRI-00001,2022,Karnataka,Belagavi,Rabi,Maize,2022-11-10,HQPM-1,1.52,Rainfed,...,6.30,80.8,52.4,87.8,Silty Loam,26.8,4.43,3.6,0.703,2.82
1,AGRI-00002,2019,Karnataka,Kalaburagi,Rabi,Maize,2019-11-25,HQPM-1,22.19,Rainfed,...,6.46,156.1,62.5,81.7,Loamy,11.9,5.06,6.4,0.707,2.33
2,AGRI-00003,2019,Punjab,Amritsar,Rabi,Wheat,2019-11-15,HD-2967,8.50,Drip Irrigated,...,7.34,59.5,52.0,28.3,Loamy,47.6,4.37,3.1,0.649,2.31
3,AGRI-00004,2017,Madhya Pradesh,Jabalpur,Rabi,Wheat,2017-10-29,HD-3086,7.48,Irrigated,...,6.83,116.7,60.3,50.1,Loamy,41.3,3.49,8.1,0.575,1.72
4,AGRI-00005,2022,Rajasthan,Bikaner,Kharif,Cotton,2022-06-04,Bunny-Bt,6.44,Rainfed,...,6.76,132.4,25.1,43.1,Alluvial,30.4,2.07,9.3,0.651,1.46

In [4]:
df['sowing_date'] = pd.to_datetime(df['sowing_date'])

In [5]:
df['sowing_year'] = df['sowing_date'].dt.year
df['sowing_month'] = df['sowing_date'].dt.month
df['sowing_day'] = df['sowing_date'].dt.day
df['sowing_day_of_year'] = df['sowing_date'].dt.dayofyear

In [6]:
df.drop('sowing_date', axis=1, inplace=True)

In [7]:
df['temperature_range_c'] = (
    df['temperature_max_c'] -
    df['temperature_min_c']
)

In [8]:
df['rainfall_per_day'] = (
    df['rainfall_mm'] /
    df['growing_season_days']
)

In [9]:
df['total_npk_kg_ha'] = (
    df['nitrogen_kg_ha'] +
    df['phosphorus_kg_ha'] +
    df['potassium_kg_ha']
)

In [10]:
df['np_ratio'] = (
    df['nitrogen_kg_ha'] /
    df['phosphorus_kg_ha'].replace(0, np.nan)
)

In [11]:
df['kn_ratio'] = (
    df['potassium_kg_ha'] /
    df['nitrogen_kg_ha'].replace(0, np.nan)
)

In [12]:
df.fillna(df.median(numeric_only=True), inplace=True)

,record_id,year,state,district,season,crop_type,seed_variety,area_sown_hectares,irrigation_type,rainfall_mm,...,yield_tonnes_per_hectare,sowing_year,sowing_month,sowing_day,sowing_day_of_year,temperature_range_c,rainfall_per_day,total_npk_kg_ha,np_ratio,kn_ratio
0,AGRI-00001,2022,Karnataka,Belagavi,Rabi,Maize,HQPM-1,1.52,Rainfed,573.7,...,2.82,2022,11,10,314,19.5,5.794949,221.0,1.541985,1.086634
1,AGRI-00002,2019,Karnataka,Kalaburagi,Rabi,Maize,HQPM-1,22.19,Rainfed,805.9,...,2.33,2019,11,25,329,14.2,7.393578,300.3,2.497600,0.523382
2,AGRI-00003,2019,Punjab,Amritsar,Rabi,Wheat,HD-2967,8.50,Drip Irrigated,343.2,...,2.31,2019,11,15,319,18.7,2.908475,139.8,1.144231,0.475630
3,AGRI-00004,2017,Madhya Pradesh,Jabalpur,Rabi,Wheat,HD-3086,7.48,Irrigated,339.7,...,1.72,2017,10,29,302,12.3,2.342759,227.1,1.935323,0.429306
4,AGRI-00005,2022,Rajasthan,Bikaner,Kharif,Cotton,Bunny-Bt,6.44,Rainfed,564.1,...,1.46,2022,6,4,155,13.5,3.016578,200.6,5.274900,0.325529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,AGRI-09996,2024,Punjab,Bathinda,Kharif,Maize,DHM-117,0.81,Rainfed,616.0,...,3.05,2024,7,16,198,10.8,5.500000,269.7,2.968045,0.371121
9996,AGRI-09997,2025,Punjab,Ludhiana,Kharif,Soybean,NRC-37,6.17,Rainfed,858.6,...,1.43,2025,7,13,194,14.4,7.037705,277.7,1.220753,0.495000
9997,AGRI-09998,2025,Rajasthan,Bikaner,Rabi,Wheat,HD-2967,4.74,Rainfed,658.0,...,2.35,2025,11,4,308,15.9,4.700000,236.8,0.916364,1.041005
9998,AGRI-09999,2023,Karnataka,Kalaburagi,Kharif,Rice,Pusa-44,2.87,Rainfed,1301.8,...,1.09,2023,7,27,208,14.9,9.787970,190.8,1.038067,0.727786
9999,AGRI-10000,2021,Punjab,Patiala,Kharif,Soybean,NRC-86,2.48,Irrigated,1048.6,...,1.31,2021,7,11,192,13.1,9.709259,220.5,12.989011,0.788494

In [13]:
df.drop('record_id', axis=1, inplace=True)

In [14]:
print("Final Shape:", df.shape)
print(df.columns.tolist())

Final Shape: (10000, 33)
['year', 'state', 'district', 'season', 'crop_type', 'seed_variety', 'area_sown_hectares', 'irrigation_type', 'rainfall_mm', 'temperature_min_c', 'temperature_max_c', 'temperature_avg_c', 'humidity_pct', 'growing_season_days', 'soil_ph', 'nitrogen_kg_ha', 'phosphorus_kg_ha', 'potassium_kg_ha', 'soil_type', 'soil_moisture_pct', 'previous_yield_tonnes_ha', 'yield_trend_pct_yoy', 'ndvi', 'yield_tonnes_per_hectare', 'sowing_year', 'sowing_month', 'sowing_day', 'sowing_day_of_year', 'temperature_range_c', 'rainfall_per_day', 'total_npk_kg_ha', 'np_ratio', 'kn_ratio']

In [15]:
df.isnull().sum()

year                        0
state                       0
district                    0
season                      0
crop_type                   0
seed_variety                0
area_sown_hectares          0
irrigation_type             0
rainfall_mm                 0
temperature_min_c           0
temperature_max_c           0
temperature_avg_c           0
humidity_pct                0
growing_season_days         0
soil_ph                     0
nitrogen_kg_ha              0
phosphorus_kg_ha            0
potassium_kg_ha             0
soil_type                   0
soil_moisture_pct           0
previous_yield_tonnes_ha    0
yield_trend_pct_yoy         0
ndvi                        0
yield_tonnes_per_hectare    0
sowing_year                 0
sowing_month                0
sowing_day                  0
sowing_day_of_year          0
temperature_range_c         0
rainfall_per_day            0
total_npk_kg_ha             0
np_ratio                    0
kn_ratio                    0
dtype: int64

In [16]:
df.head()

,year,state,district,season,crop_type,seed_variety,area_sown_hectares,irrigation_type,rainfall_mm,temperature_min_c,...,yield_tonnes_per_hectare,sowing_year,sowing_month,sowing_day,sowing_day_of_year,temperature_range_c,rainfall_per_day,total_npk_kg_ha,np_ratio,kn_ratio
0,2022,Karnataka,Belagavi,Rabi,Maize,HQPM-1,1.52,Rainfed,573.7,17.5,...,2.82,2022,11,10,314,19.5,5.794949,221.0,1.541985,1.086634
1,2019,Karnataka,Kalaburagi,Rabi,Maize,HQPM-1,22.19,Rainfed,805.9,17.3,...,2.33,2019,11,25,329,14.2,7.393578,300.3,2.497600,0.523382
2,2019,Punjab,Amritsar,Rabi,Wheat,HD-2967,8.50,Drip Irrigated,343.2,7.5,...,2.31,2019,11,15,319,18.7,2.908475,139.8,1.144231,0.475630
3,2017,Madhya Pradesh,Jabalpur,Rabi,Wheat,HD-3086,7.48,Irrigated,339.7,14.9,...,1.72,2017,10,29,302,12.3,2.342759,227.1,1.935323,0.429306
4,2022,Rajasthan,Bikaner,Kharif,Cotton,Bunny-Bt,6.44,Rainfed,564.1,20.3,...,1.46,2022,6,4,155,13.5,3.016578,200.6,5.274900,0.325529

In [17]:
df.to_csv("../data/processed/final_features.csv", index=False)

**Feature-engineered dataset saved successfully!**